#!/bin/sh -e
#

cd /ifs

apt update
apt install -y apt-transport-https busybox-static curl

curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
apt install -y mariadb-backup percona-xtrabackup-24

# init system

chmod +x `grep '^#!/bin' -rl /ifs`

ln -s /bin/busybox /sbin/init
ln -s /bin/busybox /sbin/crond

rm -rf /etc/cron*
for spl in hourly daily weekly monthly; do
    mkdir -p /etc/cron.$spl
done

cp -a /ifs/etc /
cp -a /ifs/usr /

# clean cache

rm -rf /var/lib/apt/lists/*
rm -rf /ifs
