#!/bin/sh -e
#

cd /bld

apt update
apt install -y apt-transport-https busybox-static curl

curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
apt install -y mariadb-backup percona-xtrabackup-24

ln -s /bin/busybox /usr/sbin/crond
mkdir -p /var/spool/cron/crontabs
cp crontabs /var/spool/cron/crontabs/root
for spl in hourly daily weekly monthly; do
    mkdir -p /etc/cron.$spl
done

rm -rf /var/lib/apt/lists/*
rm -rf /bld
